version: '3'
services:
  postgresql:
    container_name: postgres-test-task-db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 1234567890Abc!
      POSTGRES_USER: root
      POSTGRES_DB: university
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - techTask
networks:
  techTask:
volumes:
  pgdata: